# Generated by Django 4.x on 2026-02-09
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_type', models.CharField(choices=[('details', 'Details'), ('qr', 'QR')], max_length=20)),
                ('file', models.FileField(upload_to='generated_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=255)),
                ('reseller_username', models.CharField(blank=True, max_length=255)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('user_count', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
